# Generated by Django 5.2.1 on 2026-06-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estados_explorados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fenomenos_comentados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lugares_visitados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('investigador', 'Investigador'), ('cazador', 'Cazador paranormal'), ('testigo', 'Testigo frecuente'), ('explorador', 'Explorador nocturno')], default='investigador', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
