# Generated by Django 6.0.5 on 2026-06-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fenomeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ovni", "OVNI"),
                            ("embrujado", "Lugar Embrujado"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                ("fecha_ocurrencia", models.DateField(blank=True, null=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="fenomenos/"),
                ),
                ("validado", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Validacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
