# Generated by Django 6.0.5 on 2026-06-02 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fenomenos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fenomeno",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validacion",
            name="fenomeno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validaciones",
                to="fenomenos.fenomeno",
            ),
        ),
        migrations.AddField(
            model_name="validacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="validacion",
            unique_together={("fenomeno", "usuario")},
        ),
    ]
