# Generated by Django 6.0.5 on 2026-06-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenomenos', '0004_fenomeno_estado_enlace_puntuacion_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenomeno',
            name='estado_moderacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
