# Generated by Django 6.0.5 on 2026-06-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenomenos', '0005_fenomeno_estado_moderacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('operativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='fenomeno',
            name='actividad',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('moderada', 'Moderada'), ('alta', 'Alta'), ('extrema', 'Extrema')], max_length=10),
        ),
    ]
