# Generated by Django 6.0.5 on 2026-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenomenos', '0006_basemilitar_fenomeno_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenomeno',
            name='descripcion_traducida',
            field=models.BooleanField(default=True),
        ),
    ]
