# Generated by Django 6.0.5 on 2026-06-02 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comentarios", "0001_initial"),
        ("fenomenos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="fenomeno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="fenomenos.fenomeno",
            ),
        ),
    ]
